version: "3.9"

services:
  backend2:
    build:
      context: ./backend2
      dockerfile: Dockerfile
    image: dockathif/gscomp292:backend
    environment:
      JAVA_TOOL_OPTIONS: "-Dserver.port=5000"
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend2
      dockerfile: Dockerfile
    image: dockathif/gscomp292:frontend
    depends_on:
      - backend2
    ports:
      - "8081:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
